#pragma once

#define PIN_LIVE_VIDEO_FEED_HORIZONTAL_JOYSTICK (A0)
#define PIN_LIVE_VIDEO_FEED_MOTOR_BTN (13)
#define PIN_LIVE_VIDEO_FEED_MOTOR_PWM (12)
#define PIN_LIVE_VIDEO_FEED_MOTOR_IN1 (11)
#define PIN_LIVE_VIDEO_FEED_MOTOR_IN2 (10)

#define PIN_NEOPIXEL_PIN (22)
