#pragma once

#include <common_pin_layout.h>

//-------------------------------------------------------------------------------------------------------------------

#define CONTROLLER_PIN_LEFT_JOYSTICK_ANALOG_X (A0)
#define CONTROLLER_PIN_LEFT_JOYSTICK_ANALOG_Y (A1)
#define CONTROLLER_PIN_LEFT_JOYSTICK_BUTTON (10)

#define CONTROLLER_PIN_RIGHT_JOYSTICK_ANALOG_X (A2)
#define CONTROLLER_PIN_RIGHT_JOYSTICK_ANALOG_Y (A3)
#define CONTROLLER_PIN_RIGHT_JOYSTICK_BUTTON (8)

#define CONTROLLER_PIN_LEFT_INDICATOR_BUTTON (22)
#define CONTROLLER_PIN_LEFT_INDICATOR_BUTTON_LED (23)

#define CONTROLLER_PIN_SPOTLIGHT_LATCHING_BUTTON (24)
#define CONTROLLER_PIN_SPOTLIGHT_LATCHING_BUTTON_LED (25)

#define CONTROLLER_PIN_SPOTLIGHT_MOMENTARY_BUTTON (26)
#define CONTROLLER_PIN_SPOTLIGHT_MOMENTARY_BUTTON_LED (27)

#define CONTROLLER_PIN_LIVE_VIDEO_FEED_OVERRIDE_BUTTON (28)
#define CONTROLLER_PIN_LIVE_VIDEO_FEED_OVERRIDE_BUTTON_LED (29)

#define CONTROLLER_PIN_RIGHT_INDICATOR_BUTTON (30)
#define CONTROLLER_PIN_RIGHT_INDICATOR_BUTTON_LED (31)

#define CONTROLLER_PIN_CORE_LIGHTS_BUTTON (32)
#define CONTROLLER_PIN_CORE_LIGHTS_BUTTON_LED (33)

#define CONTROLLER_PIN_EXTRA_LIGHT_01_BUTTON (34)
#define CONTROLLER_PIN_EXTRA_LIGHT_01_BUTTON_LED (35)

#define CONTROLLER_PIN_EXTRA_LIGHT_02_BUTTON (36)
#define CONTROLLER_PIN_EXTRA_LIGHT_02_BUTTON_LED (37)

#define CONTROLLER_PIN_EXTRA_LIGHT_03_BUTTON (38)
#define CONTROLLER_PIN_EXTRA_LIGHT_03_BUTTON_LED (39)

#define CONTROLLER_PIN_FUNCTION_BUTTON (40)
#define CONTROLLER_PIN_FUNCTION_BUTTON_LED (41)

//-------------------------------------------------------------------------------------------------------------------





